# Use X-Forwarded-*-headers for absolute URL resolution
server:
  forward-headers-strategy: framework
  shutdown: graceful
  port: ${PORT:8080}
  error:
    include-message: always

spring:
  application:
    name: plantevernjournal-innlesing-api

  cloud:
    gcp:
      core:
        enabled: true
      secretmanager:
        enabled: true

  config:
    import: "sm@"

  profiles:
    active: local

eppo:
  token: ${sm@eppo-token}
  uri: "https://data.eppo.int/api/rest/1.0"

nats:
  url: tls://connect.nats.mattilsynet.io:4222
  creds: ${sm@nats-creds}
