# Use X-Forwarded-*-headers for absolute URL resolution
server:
  forward-headers-strategy: framework
  shutdown: graceful
  port: ${PORT:8080}
  error:
    include-message: always

spring:
  application:
    name: plantevernjournal-innlesing-api

  cloud:
    gcp:
      core:
        enabled: true
      secretmanager:
        enabled: true

  config:
    import: "sm@"

  profiles:
    active: staging

eppo:
  api:
    uri: "https://api.eppo.int/gd/v2"
    token: ${sm@eppo-api-token}

nats:
  url: tls://connect.nats.mattilsynet.io:4222
  creds: ${sm@nats-creds}

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.oauth2.server.resource.web.server: TRACE
